CommerceWeavers/SyliusTpayPlugin

- config/services/payum/action.php
- config/services/tpay.php
- src/Form/Type/TpayPaymentDetailsType.php
- src/Payum/Action/Api/CreateBlikLevelZeroTransactionAction.php
- src/Tpay/Factory/CreateBlikLevelZeroPaymentPayloadFactory.php
- src/Tpay/Factory/CreateBlikLevelZeroPaymentPayloadFactoryInterface.php
- tests/Unit/Payum/Action/Api/CreateBlikLevelZeroTransactionActionTest.php
- tests/Unit/Payum/Action/CaptureActionTest.php
> BLIK payments improvements

- .github/workflows/_matrix.json
> Fix the CI matrix

- config/services/api/command.php
- config/services/api/factory.php
- src/Api/Command/PayByRedirect.php
- src/Api/Command/PayByRedirectHandler.php
- src/Api/Command/PayHandler.php
- src/Api/Factory/NextCommand/PayByRedirectFactory.php
- src/Model/PaymentDetails.php
- src/Payum/Action/Api/CreateRedirectBasedTransactionAction.php
- src/Tpay/Factory/CreateRedirectBasedPaymentPayloadFactory.php
- tests/Api/Responses/shop/paying_for_orders_by_redirect/test_paying_with_redirect_based_payment_type.json
- tests/Api/Shop/PayingForOrdersByRedirectTest.php
- tests/Unit/Api/Command/PayByBlikHandlerTest.php
- tests/Unit/Api/Command/PayByCardHandlerTest.php
- tests/Unit/Api/Command/PayByRedirectHandlerTest.php
- tests/Unit/Api/Command/PayHandlerTest.php
- tests/Unit/Payum/Action/Api/CreateBlikLevelZeroTransactionActionTest.php
- tests/Unit/Payum/Action/Api/CreateCardTransactionActionTest.php
- tests/Unit/Payum/Action/Api/CreateRedirectBasedTransactionActionTest.php
- tests/Unit/Payum/Action/Api/NotifyActionTest.php
- tests/Unit/Payum/Action/Api/PayWithCardActionTest.php
> Add support for redirect-based payments in API

- config/services/tpay.php
- src/Tpay/Factory/CreateRedirectBasedPaymentPayloadFactory.php
- tests/Unit/Tpay/Factory/CreateRedirectBasedPaymentPayloadFactoryTest.php
- translations/messages.en.yaml
- translations/messages.pl.yaml
Add translation of api description payload
Closes #51
> Provide translatable description for TPay call

- assets/shop/checkout_complete_entrypoint.js
- assets/shop/js/card_form.js
- assets/shop/js/retry_payment.js
- assets/shop/order_show_entrypoint.js
- config/config/sylius_template_events.php
- src/Tpay/Security/Notification/Factory/BasicPaymentFactory.php
- templates/shop/cart/complete/_blik.html.twig
- templates/shop/cart/complete/_card.html.twig
- templates/shop/order/pay/_blik.html.twig
- templates/shop/order/pay/_card.html.twig
- templates/shop/payment/_blik.html.twig
- templates/shop/payment/_card.html.twig
- tests/E2E/Checkout/TpayPaymentCheckoutTest.php
- tests/E2E/Helper/Order/TpayTrait.php
- tests/E2E/Order/TpayRetryOrChangePaymentOrderTest.php
> Support retrying or changing to card payment method

- assets/shop/checkout_complete_entrypoint.js
- assets/shop/js/card_form.js
- src/Form/Type/TpayCardType.php
- templates/shop/payment/_card.html.twig
- tests/E2E/Checkout/TpayPaymentCheckoutTest.php
- tests/E2E/Helper/Order/TpayTrait.php
- tests/E2E/Order/TpayRetryOrChangePaymentOrderTest.php
- translations/validators.en.yaml
Solves 1st subissue of #107 
After:
> Remove Card holder name and add missing translation

- config/config/sylius_template_events.php
- config/services/context_provider.php
- src/ContextProvider/RegulationsUrlContextProvider.php
- src/Tpay/TpayPolicy.php
- templates/shop/cart/complete/_apple_pay_regulations.html.twig
- templates/shop/cart/complete/_google_pay_regulations.html.twig
- templates/shop/cart/complete/_payByLink.html.twig
- templates/shop/cart/complete/_visaMobile.html.twig
- templates/shop/order/pay/_apple_pay_regulations.html.twig
- templates/shop/order/pay/_google_pay_regulations.html.twig
- templates/shop/payment/_blik.html.twig
- templates/shop/payment/_card.html.twig
- templates/shop/payment/_payByLink.html.twig
- translations/messages.en.yaml
- translations/messages.pl.yaml
part of #107 
example for apple pay:
> Add regulations for payments in checkout and retry payment

- translations/messages.en.yaml
- translations/messages.pl.yaml
part of #107 
Changed according to documentation provided by Tpay
> Change translation messages

- src/ContextProvider/BankListContextProvider.php
- src/Form/Extension/CompleteTypeExtension.php
- templates/bundles/SyliusShopBundle/Checkout/Complete/_navigation.html.twig
- templates/shop/cart/complete/_apple_pay.html.twig
- templates/shop/cart/complete/_apple_pay_regulations.html.twig
- templates/shop/cart/complete/_blik.html.twig
- templates/shop/cart/complete/_card.html.twig
- templates/shop/cart/complete/_google_pay.html.twig
- templates/shop/cart/complete/_google_pay_regulations.html.twig
- templates/shop/cart/complete/_payByLink.html.twig
- templates/shop/cart/complete/_visaMobile.html.twig
- tests/E2E/Checkout/FreePaymentCheckoutTest.php
- tests/E2E/Resources/fixtures/addressed_free_cart.yaml
- tests/E2E/Resources/fixtures/free_shipping_method.yaml
- tests/Unit/ContextProvider/BankListContextProviderTest.php
> Solve 500 error on orders of 0.00 total

- templates/shop/cart/complete/_apple_pay_regulations.html.twig
- templates/shop/cart/complete/_google_pay_regulations.html.twig
- templates/shop/cart/complete/_payByLink.html.twig
- templates/shop/cart/complete/_visaMobile.html.twig
- templates/shop/order/pay/_apple_pay_regulations.html.twig
- templates/shop/order/pay/_google_pay_regulations.html.twig
- templates/shop/partial/_policies.html.twig
- templates/shop/payment/_blik.html.twig
- templates/shop/payment/_card.html.twig
- templates/shop/payment/_payByLink.html.twig
- templates/shop/payment/_visaMobile.html.twig
- translations/messages.en.yaml
- translations/messages.pl.yaml
> Change links, refactor template, change links to point to new page

- src/Tpay/Factory/CreateRedirectBasedPaymentPayloadFactory.php
- tests/Unit/Tpay/Factory/CreateRedirectBasedPaymentPayloadFactoryTest.php
> Create Payer Payload only from required and existing data

- config/services/form.php
- config/services/refunding.php
- src/Form/Type/TpayGatewayConfigurationType.php
- src/Payum/Factory/TpayGatewayFactory.php
`Client ID` and `Client Secret` are not allowed to be blank anymore 🎉 
#129
> Add a basic form validation for the TpayGatewayConfiguration

- src/Controller/DisplayPaymentFailedPageAction.php
- src/Model/PaymentDetails.php
- src/Payum/Action/Api/CreateBlikLevelZeroTransactionAction.php
- src/Payum/Processor/CreateTransactionProcessor.php
- templates/shop/cart/complete/payment_failed.html.twig
- tests/Api/Shop/PayingForOrdersByBlikTest.php
- tests/E2E/Checkout/TpayPaymentCheckoutTest.php
- tests/Helper/PaymentDetailsHelperTrait.php
- tests/Unit/Payum/Action/Api/CreateBlikLevelZeroTransactionActionTest.php
- tests/Unit/Tpay/Processor/CreateTransactionProcessorTest.php
- tests/mockoon_tpay.json
> Invalid Blik code redirects to error page

- src/Form/Type/TpayGatewayConfigurationType.php
> Do not throw exception on gateway edit and create

- assets/shop/checkout_complete_entrypoint.js
- assets/shop/js/blik_code.js
- assets/shop/order_show_entrypoint.js
- templates/shop/payment/_blik.html.twig
> Prevent providing BLIK code longer than 6 characters and with non-digits

- translations/messages.en.yaml
> Adjust blik code translation

- src/Form/Type/TpayGatewayConfigurationType.php
- tests/Unit/Form/Type/TpayGatewayConfigurationTypeTest.php
- translations/messages.en.yaml
- translations/messages.pl.yaml
> Add visa mobile option to gateway configuration

- translations/messages.en.yaml
- translations/messages.pl.yaml
> Improve credit card translations

- config/config/sylius_fixtures.php
- config/services/api/factory.php
- config/services/payum/action.php
- config/services/redirect_payment/form.php
- config/services/redirect_payment/form/type.php
- config/services/redirect_payment/payum.php
- config/services/redirect_payment/payum/action.php
- config/services/redirect_payment/payum/factory.php
- src/Api/Factory/NextCommand/PayByRedirectFactory.php
- src/RedirectPayment/Form/Type/GatewayConfigurationType.php
- src/RedirectPayment/Payum/Action/CreateRedirectBasedTransactionAction.php
- src/RedirectPayment/Payum/Factory/GatewayFactory.php
- tests/Api/DataFixtures/shop/blik_payment_method.yml
- tests/Api/DataFixtures/shop/cancelling_payment/payment_method.yml
- tests/Api/DataFixtures/shop/paying_for_orders_by_card/payment_method.yml
- tests/E2E/Resources/fixtures/common/payment_method.yaml
- tests/Unit/RedirectPayment/Payum/Action/CreateRedirectBasedTransactionActionTest.php
- translations/messages.en.yaml
- translations/messages.pl.yaml
> Extract Tpay Redirect as a separate payment method

- config/config/sylius_fixtures.php
- config/services/google_pay_payment/form.php
- config/services/google_pay_payment/form/type.php
- config/services/google_pay_payment/payum.php
- config/services/google_pay_payment/payum/action.php
- config/services/google_pay_payment/payum/factory.php
- config/services/google_pay_payment/validator.php
- config/services/payum/action.php
- config/services/validator.php
- config/validation/Pay.xml
- src/Form/Type/TpayPaymentDetailsType.php
- src/GooglePayPayment/Form/Type/GatewayConfigurationType.php
- src/GooglePayPayment/Payum/Action/CreateGooglePayTransactionAction.php
- src/GooglePayPayment/Payum/Factory/GatewayFactory.php
- src/GooglePayPayment/Validator/Constraint/EncodedGooglePayToken.php
- src/GooglePayPayment/Validator/Constraint/EncodedGooglePayTokenValidator.php
- templates/bundles/SyliusShopBundle/Checkout/Complete/_navigation.html.twig
- templates/shop/cart/complete/_google_pay.html.twig
- templates/shop/order/pay/_apple_pay_regulations.html.twig
- templates/shop/order/pay/_google_pay_regulations.html.twig
- tests/Api/DataFixtures/shop/paying_for_orders_by_google_pay.yml
- tests/Api/Shop/PayingForOrdersByGooglePayTest.php
- tests/E2E/Resources/fixtures/common/payment_method.yaml
- tests/Unit/GooglePayPayment/Payum/Action/CreateGooglePayTransactionActionTest.php
- tests/Unit/GooglePayPayment/Validator/Constraint/EncodedGooglePayTokenValidatorTest.php
- translations/messages.en.yaml
- translations/messages.pl.yaml
> Extract Tpay Google Pay as a separate payment method

- config/config/sylius_fixtures.php
- config/services/payum/action.php
- config/services/tpay.php
- config/services/visa_mobile_payment/form.php
- config/services/visa_mobile_payment/form/type.php
- config/services/visa_mobile_payment/payum.php
- config/services/visa_mobile_payment/payum/action.php
- config/services/visa_mobile_payment/payum/factory.php
- config/validation/Pay.xml
- src/Payum/Action/Api/CreateVisaMobileTransactionAction.php
- src/Repository/PaymentMethodRepositoryInterface.php
- src/Repository/PaymentMethodTrait.php
- src/Tpay/GatewayName.php
- src/Tpay/Provider/ValidTpayChannelListProvider.php
- src/VisaMobilePayment/Form/Type/GatewayConfigurationType.php
- src/VisaMobilePayment/Payum/Action/CreateVisaMobileTransactionAction.php
- src/VisaMobilePayment/Payum/Factory/GatewayFactory.php
- templates/shop/cart/complete/_visaMobile.html.twig
- templates/shop/order/pay/_visaMobile.html.twig
- tests/Api/DataFixtures/shop/paying_for_orders_by_card/payment_method.yml
- tests/E2E/Resources/fixtures/common/payment_method.yaml
- tests/Unit/Tpay/Provider/ValidTpayChannelListProviderTest.php
- tests/Unit/VisaMobilePayment/Payum/Action/CreateVisaMobileTransactionActionTest.php
- translations/messages.en.yaml
- translations/messages.pl.yaml
> Extract Tpay Visa Mobile as a separate payment method

- .github/workflows/_matrix.json
> [Maintenance] Support Sylius 1.14

- src/CommerceWeaversSyliusTpayPlugin.php
- src/Payum/Factory/TpayGatewayFactory.php
> Add build info to client name to ease debugging

- .platform.app.yaml
> Optimize node_modules cache for Platform.sh deployment

- assets/shop/js/blik_code.js
- config/services/apple_pay_payment/twig/component.php
- config/services/apple_pay_payment/twig/hook.php
- config/twig_hooks/admin/payment_method/create.php
- config/twig_hooks/admin/payment_method/form.php
- config/twig_hooks/admin/payment_method/update.php
- config/twig_hooks/shop/checkout/complete.php
- src/ApplePayPayment/Controller/InitApplePayPaymentAction.php
- src/ApplePayPayment/Twig/Hooks/ConfirmOrderButtonHookable.php
- templates/admin/payment_method/apple_pay/gateway_configuration/merchant_id.html.twig
- templates/shop/cart/complete/apple_pay.html.twig
- tests/Unit/ApplePayPayment/Twig/Hooks/ConfirmOrderButtonHookableTest.php
> Bring back the ApplePay functionality

- src/Api/Factory/NextCommand/PayByRedirectFactory.php
- src/Api/Validator/Constraint/NotBlankIfGatewayNameEqualsValidator.php
- src/Api/Validator/Constraint/OneOfPropertiesRequiredIfGatewayNameEqualsValidator.php
- src/Payum/Action/Api/BasePaymentAwareAction.php
- src/Payum/Action/ResolveNextRouteAction.php
- src/Payum/Processor/CreateTransactionProcessor.php
- src/RedirectPayment/Payum/Action/CreateRedirectBasedTransactionAction.php
- src/Refunding/Dispatcher/RefundDispatcher.php
- src/Tpay/Provider/ValidTpayChannelListProvider.php
- templates/shop/cart/complete/apple_pay.html.twig
- templates/shop/cart/complete/blik.html.twig
- templates/shop/cart/complete/card.html.twig
- templates/shop/cart/complete/google_pay.html.twig
- templates/shop/cart/complete/pay_by_link.html.twig
- templates/shop/cart/complete/visa_mobile.html.twig
- tests/Unit/Api/Validator/Constraint/NotBlankIfGatewayNameEqualsValidatorTest.php
- tests/Unit/Api/Validator/Constraint/OneOfPropertiesRequiredIfGatewayNameEqualsValidatorTest.php
- tests/Unit/ApplePayPayment/Payum/Action/CreateApplePayTransactionActionTest.php
- tests/Unit/BlikPayment/Payum/Action/CreateBlikLevelZeroTransactionActionTest.php
- tests/Unit/CardPayment/Payum/Action/CreateCardTransactionActionTest.php
- tests/Unit/GooglePayPayment/Payum/Action/CreateGooglePayTransactionActionTest.php
- tests/Unit/Payum/Action/ResolveNextRouteActionTest.php
- tests/Unit/RedirectPayment/Payum/Action/CreateRedirectBasedTransactionActionTest.php
- tests/Unit/Refunding/Dispatcher/RefundDispatcherTest.php
- tests/Unit/Tpay/Processor/CreateTransactionProcessorTest.php
- tests/Unit/Tpay/Provider/ValidTpayChannelListProviderTest.php
- tests/Unit/VisaMobilePayment/Payum/Action/CreateVisaMobileTransactionActionTest.php
> [Payments] Use factory name instead of gateway name 

- src/CardPayment/Tpay/Factory/CreateCardPaymentPayloadFactory.php
- src/Tpay/Factory/CreateVisaMobilePaymentPayloadFactory.php
- tests/Unit/CardPayment/Tpay/Factory/CreateCardPaymentPayloadFactoryTest.php
- tests/Unit/Tpay/Factory/CreateVisaMobilePaymentPayloadFactoryTest.php
This PR reverts https://github.com/CommerceWeavers/SyliusTpayPlugin/pull/306 and https://github.com/CommerceWeavers/SyliusTpayPlugin/pull/305
> [DX-1298, DX-1300] - Revert changes needed temprorarly
